In [1]:
l = [11, -2, 6, 9, 42] 
l

[11, -2, 6, 9, 42]

## Lista 
la lista può contenere variabile di tipo diverso tra loro

### Oerazioni sulle lusta 

l'operatore * riproduce gli elementi dentro la lista


In [2]:
lst = [4] * 5 
lst

[4, 4, 4, 4, 4]

### Per aggiungere elementi nella lista
si può usare il *metodo* append con la dot notation: lista.append(elemento da aggiungere in fondo)

- l'operatore + concatena 2 liste, in alternativa si può usare .extend()

In [5]:
lst.append(42)
lst

l.extend(lst)
l

[11, -2, 6, 9, 42, 4, 4, 4, 4, 4, 42, 42, 42]

con le liste posso selezionare gli elementi con le parentesi [] passando il numero dell'indice, se parto dalla fine della lista inizio da -1. quindi l'ultimo elemento della lista ha indice -1


In [10]:
anno = [2009, 2010, 2011, 2012]
ultimo_anno = anno[-1]
ultimo_anno

2012

Selezione parti di liste: slicing

si usa l'operatore : tra quadre quindi anno[0:2] parte dal primo indice compreso e arriva fino all'indice dopo il : escluso
`lista[start:stop]`
esempio per cancellare parte della lista anno:


In [11]:
del anno[0:2]
anno

[2011, 2012]

Posso anche eliminare elementi semplicemente chiamandoli


In [12]:
nomi = ["Anna", "Adriana", "Maria", "Susanna"]
nomi.remove("Susanna")
nomi

['Anna', 'Adriana', 'Maria']

### Occhio al range
Se chiamo una lista a un indice che non esiste, mi sputa un errore IndexErro out of index.

---

### Cicli for
- Esercizio:
  creare una lista di int da 0 a 10 e ciclare sulla lista per creare una nuova lista con i quadrati dei numeri da 0 a 10
  

In [13]:
for pippo in l:
    print(pippo)

11
-2
6
9
42
4
4
4
4
4
42
42
42


pippo è una variabile che viene creata per essere usata nel ciclo, non è necessario che sia dichiarata prima

**Posso usare lo slicing** sull'oggetto che fa da iteratore, dandogli uno start uno stop ed eventualmente anche uno step. 

`[start:stop:step]`


#### Range

Funzione che produce una sequenza di numeri dallo start allo stop e se indicato incrementa di uno step dato.
Di defaut lo step è 1
Per produrre una lista di numeri pari da 1 a 100 devo invocare la fz range con start 1, stop 101, step 2:

In [24]:
lista_pari = list(range(0,101,2))
type(lista_pari)

In [23]:
range_pari = range(0,101,2)
range_pari

range(0, 101, 2)

In [29]:
lst1 = list(range(0,11))
square = lis5 > 6 and 6 > 5 

# better = [num**2 for num in lst1]
# better

0
0
1
1
2
4
3
9
4
16
5
25
6
36
7
49
8
64
9
81
10
100


[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

### List comprehension


In [31]:
cube = [pow(n,3) for n in range(11)]
cube

[0, 1, 8, 27, 64, 125, 216, 343, 512, 729, 1000]

## DICTIONARY!!!! 
Funzione dict per creare dictionary

sono key value pair, le key devono essere univoche!

{'key':'value'} oppure {'key': {'key1': 'value1' }} oppure {'key': [1,2,3,3,4,55,42,10]}

il valore può essere un altro dict o una lista o qualsiasi altro tipo di valore

In [32]:
dictionary_vuoto = {}
dizionario_vuoto = dict()

per richiamare tutti i valori del dict uso il metodo values() per avere tutte le key uso keys()

si può usare lo zip su due liste con uguale lenght per creare un dizionario



## tuple 
SONO IMMUTABILI
Non possono essere riassegnate 

Sono dichiarate tra parentesi tonde

il metodo sort nelle tuple ritorna una lista con gli stessi elementi ordinati



In [109]:
tup1 = (1,2,3)
tup2 = (7,9,6)

tuples = [tup1, tup2]
tuples

[(1, 2, 3), (7, 9, 6)]

In [35]:
#selezione elementi nestati
tuples[1][2] #ritorna il 6 ovvero l'ultimo elemento della seconda tupla

6

## Array

Gli array non sono nativi in python, si trovano nella libreria numpy solitamente importati con l'alias np

In [37]:
import numpy as np

country = np.array(["USA", "JPN", "IT"])
country

array(['USA', 'JPN', 'IT'], dtype='<U3')

### Shape dell'array

metodo che torna il numero delle righe e delle colonne

Array monodimensionali np.array([]) 
array più dimensioni 

`np.array([[1,2,3],[4,5,6]])`

In [45]:
#array multidimensioni

y = np.array([[2,3,1,2], [0,4,5,6]]) # 2 righe, 4 colonne
y

array([[2, 3, 1, 2],
       [0, 4, 5, 6]])

In [47]:
y1 = np.array([[2,3,1,2], [0,4,5,6], []]) #rispettare il numero di colonne nei vettori sennò da errore
y1

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

In [48]:
y2 = np.array([[2,3,1,2], [0,4,5,6], [0,0,0,0]]) # 3 righe 3 colonne
y2

array([[2, 3, 1, 2],
       [0, 4, 5, 6],
       [0, 0, 0, 0]])

In [54]:
#generare matrici di zero e/o uno

w = np.zeros((3,2)) #devo passare una tupla a 2 valori o shape di un'altra matrice 

z = np.zeros(y2.shape)
z

u = np.ones(y2.shape)
u

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [56]:
# Range negli array 
ran = np.arange(1,10,2) #è possibile dare anche il tipo di variabile don dtype 
ran

array([1, 3, 5, 7, 9])

In [60]:
#LinSpace 
# crea un array da un num iniziale a uno finale con tanti elementi quanti indicati. La differenza tra numeri adiacenti è la stessa in tutto l'array

lin_spacing = np.linspace(1., 12, 8)
lin_spacing

array([ 1.        ,  2.57142857,  4.14285714,  5.71428571,  7.28571429,
        8.85714286, 10.42857143, 12.        ])

In [61]:
###ma che belli gli array che ci puoi fare la matematica 
alfa = np.arange(30)
alfa

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [63]:
alfa / 3 #divide ogni elemento dell'array per 3

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667, 2.        , 2.33333333, 2.66666667, 3.        ,
       3.33333333, 3.66666667, 4.        , 4.33333333, 4.66666667,
       5.        , 5.33333333, 5.66666667, 6.        , 6.33333333,
       6.66666667, 7.        , 7.33333333, 7.66666667, 8.        ,
       8.33333333, 8.66666667, 9.        , 9.33333333, 9.66666667])

In [66]:
alfa.sort()
alfa

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [68]:
beta = np.linspace(0, 30, 30)
beta

array([ 0.        ,  1.03448276,  2.06896552,  3.10344828,  4.13793103,
        5.17241379,  6.20689655,  7.24137931,  8.27586207,  9.31034483,
       10.34482759, 11.37931034, 12.4137931 , 13.44827586, 14.48275862,
       15.51724138, 16.55172414, 17.5862069 , 18.62068966, 19.65517241,
       20.68965517, 21.72413793, 22.75862069, 23.79310345, 24.82758621,
       25.86206897, 26.89655172, 27.93103448, 28.96551724, 30.        ])

In [69]:
alfa + beta

array([ 0.        ,  2.03448276,  4.06896552,  6.10344828,  8.13793103,
       10.17241379, 12.20689655, 14.24137931, 16.27586207, 18.31034483,
       20.34482759, 22.37931034, 24.4137931 , 26.44827586, 28.48275862,
       30.51724138, 32.55172414, 34.5862069 , 36.62068966, 38.65517241,
       40.68965517, 42.72413793, 44.75862069, 46.79310345, 48.82758621,
       50.86206897, 52.89655172, 54.93103448, 56.96551724, 59.        ])

---

# Algebra Booleana

**True** & **False**


In [70]:
True + True #è come bestemmiare!!!

2

In [71]:
#Espressioni Booleane 

50 >= 40.9999

True

In [72]:
10//2 == 11//2

True

In [73]:
'ciao' == 'goodbay'

False

In [75]:
'ciao' != 'Ciao' # case sensitive

True

#### And 

In [76]:
5 > 6 and 6 > 5 

False

In [77]:
6>5 and 7>4

True

#### Or

In [78]:
5 > 6 or 6 > 5 

True

#### not 

In [79]:
not 3 == 3 #nega l'espressione

False

---

### Esercizio
Validatori

verificare se la variabile età è maggiore di 18 anni, il programma dovrebbe controllare il valore della variabile e dare un output per ogni caso.

In [95]:
eta = 19

if eta < 18:
    print("Stai fuori, sei minorenne")
else:
    print("Sei maggiorenne, entra!")


Sei maggiorenne, entra!


In [100]:
# Else If elif
eta = -12

if eta <= 0:
    print('Hai inserito un numero errato')
elif eta < 10:
    print('sei un bimbo')
elif eta <= 18:
    print('sei un regaz')
elif eta < 50:
    print('boomer')
else:
    print('vecchio')

Hai inserito un numero errato


In [93]:
patente = True

if eta >= 18 and patente:
    print("se hai il cash ti do la macchina!")
elif eta < 18:
    print("vai alla hertz a vedere cosa ti dicono...")

se hai il cash ti do la macchina!


In [102]:
# INPUT

in_data = input('inserire qualcosa')
in_data

'hi'

In [103]:
nome = input('inserire il tuo nome ')
print('buon pomeriggio ' + nome + '!')


buon pomeriggio pg!


In [104]:
####Input numeri
#input prende solo stringhe quindi dobbiamo convertire i numeri se vogliamo usarli in operazioni aritmetiche 

eta = input('quanti anni hai? ')
print("Ciao " + nome + " al momento hai " + eta + " anni.\n"+ "L'anno prossimo avrai " + str(int(eta) + 1))

Ciao pg al momento hai 34 anni.
L'anno prossimo avrai 35


In [108]:
### Noleggio check

patente = input('inserisci una lettera qualsiasi se hai la patente')

eta = input('quanti anni hai?')
if eta >= 18 and patente:
    """se patente è stringa vuota il booleano è False se c'è qualsiasi
    cosa torna True"""
    print("puoi noleggiare... se hai la grana")
else:
    print("ciccia")


1


### While loop

Per cicli di cui non conosco a priori il numero di iterazioni da compiere

In [2]:
##While

while True: #è una bestemmia
    """chiede numeri interi in input finchè non viene inserito il numero 100"""
    numero = int(input("inserisci un numero"))
    if numero >= 100:
        print(f"il numero inserito è {numero}")
        break




il numero inserito è 100


In [7]:
n = 0
print(n)

while n < 100:
    n = int(input("inserisci un numero"))
    print(f"il numero inserito è {n}")

0
il numero inserito è 12
il numero inserito è 32
il numero inserito è 43
il numero inserito è 100
il numero inserito è 100
il numero inserito è 120
